### PR TITLE
Avoid asking for permissions twice

### PR DESCRIPTION
**Pull request by optout21**
See https://github.com/schmich/instascan/issues/110

No permission asked during getCameras(), option to skip _ensureAccess().

### CODE REVIEW

**Review by kidanam — APPROVED** [review]

**Comment by kidanam** [comment]
Does this work? how do I use this new change?

**Comment by optout21** [comment]
Yes, double call is avoided with this proposed change.  I believe it solves the problems reported in issue #110 .

**Comment by Maxwellkurt0407** [comment]
> See #110
> 
> No permission asked during getCameras(), option to skip _ensureAccess().

How do I use this in the browser?

**Comment by optout21** [comment]
> How do I use this in the browser?

What do you mean?  How to use instascan in a browser?  It is HTML/web based.

**Comment by Maxwellkurt0407** [comment]
> > How do I use this in the browser?
> 
> What do you mean? How to use instascan in a browser? It is HTML/web based.

Amateur developer here, I apologize. I mean, how do I include the changes in the instascan.min.js file? Is there a way to do that?

**Comment by optout21** [comment]
To integrate the changes for trying out?  Since there are only 2-3 lines changed, you can just look at Files Changed, and copy the changes.  Or you can checkout the branch of the pr:

```
git remote add mikroncoin https://github.com/mikroncoin/instascan.git
git fetch mikroncoin
git checkout -b pr/213 -t mikroncoin/no-double-perm
```

To take over the changes for good, you just Merge the PR :)

**Comment by optout21** [comment]
Closing after 4+ years

**Pull request closed without merging**
